# Generated by Django 3.1.1 on 2020-09-26 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 26, 11, 7, 21, 235881, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 26, 11, 7, 21, 235881, tzinfo=utc)),
        ),
    ]
